on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: staging
      - run: |
          echo "Hello GitHub Actions!" >> hello.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated on staging"
          git push
